# #print('Hello world')
# def turn_right():
#     turn_left()
#     turn_left()
#     turn_left()
# def jump():
#     turn_left()
#     move()
#     turn_right()
#     move()
#     turn_right()
#     move()
#     turn_left()
# def movethree():
#     move()
#     move()
#     move()
# jump()
# movethree()

# jump()
# movethree()
# jump()
# jump()
# jump()
# jump()